[package]
name = "rust-simple-blockchain"
version = "0.1.0"
edition = "2021"
[workspace]
members = [
    "crates/main",
    "crates/core",
    "crates/utils"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


